# Generated by Django 2.2.7 on 2019-11-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191106_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='last_mod_time',
            new_name='last_mod_date',
        ),
    ]
