# Generated by Django 2.2.7 on 2019-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191106_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view',
            field=models.BigIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
